#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CryptMe.Resource", IsApplication=true)]

namespace CryptMe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int InputTextView = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int InputTextViewLayout = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int Keyboard1LineLayout = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int Keyboard2LineLayout = 2131099676;
			
			// aapt resource value: 0x7f060026
			public const int Keyboard3LineLayout = 2131099686;
			
			// aapt resource value: 0x7f060006
			public const int KeyboardNumbersLineLayout = 2131099654;
			
			// aapt resource value: 0x7f060030
			public const int KeyboardUtilLineLayout = 2131099696;
			
			// aapt resource value: 0x7f060002
			public const int MainViewLayout = 2131099650;
			
			// aapt resource value: 0x7f060033
			public const int NewKeys = 2131099699;
			
			// aapt resource value: 0x7f060001
			public const int OutTextView = 2131099649;
			
			// aapt resource value: 0x7f060034
			public const int ShowKeys = 2131099700;
			
			// aapt resource value: 0x7f060000
			public const int TranslatedLayout = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int button0 = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int button1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int button2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int button3 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int button4 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int button5 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int button6 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button7 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button8 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button9 = 2131099663;
			
			// aapt resource value: 0x7f06001d
			public const int buttonA = 2131099677;
			
			// aapt resource value: 0x7f06002c
			public const int buttonB = 2131099692;
			
			// aapt resource value: 0x7f06002f
			public const int buttonBSP = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int buttonC = 2131099690;
			
			// aapt resource value: 0x7f06001f
			public const int buttonD = 2131099679;
			
			// aapt resource value: 0x7f060014
			public const int buttonE = 2131099668;
			
			// aapt resource value: 0x7f060032
			public const int buttonEnter = 2131099698;
			
			// aapt resource value: 0x7f060020
			public const int buttonF = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int buttonG = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int buttonH = 2131099682;
			
			// aapt resource value: 0x7f060019
			public const int buttonI = 2131099673;
			
			// aapt resource value: 0x7f060023
			public const int buttonJ = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int buttonK = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int buttonL = 2131099685;
			
			// aapt resource value: 0x7f06002e
			public const int buttonM = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int buttonN = 2131099693;
			
			// aapt resource value: 0x7f06001a
			public const int buttonO = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int buttonP = 2131099675;
			
			// aapt resource value: 0x7f060012
			public const int buttonQ = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int buttonR = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int buttonS = 2131099678;
			
			// aapt resource value: 0x7f060031
			public const int buttonSpace = 2131099697;
			
			// aapt resource value: 0x7f060027
			public const int buttonSwitch = 2131099687;
			
			// aapt resource value: 0x7f060016
			public const int buttonT = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int buttonU = 2131099672;
			
			// aapt resource value: 0x7f06002b
			public const int buttonV = 2131099691;
			
			// aapt resource value: 0x7f060013
			public const int buttonW = 2131099667;
			
			// aapt resource value: 0x7f060029
			public const int buttonX = 2131099689;
			
			// aapt resource value: 0x7f060017
			public const int buttonY = 2131099671;
			
			// aapt resource value: 0x7f060028
			public const int buttonZ = 2131099688;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int AppMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int NewKeys = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ShowKeys = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
