#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CryptMe.Resource", IsApplication=true)]

namespace CryptMe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int InputTextView = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int InputTextViewLayout = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int Keyboard1LineLayout = 2131034126;
			
			// aapt resource value: 0x7f050019
			public const int Keyboard2LineLayout = 2131034137;
			
			// aapt resource value: 0x7f050023
			public const int Keyboard3LineLayout = 2131034147;
			
			// aapt resource value: 0x7f050003
			public const int KeyboardNumbersLineLayout = 2131034115;
			
			// aapt resource value: 0x7f05002d
			public const int KeyboardUtilLineLayout = 2131034157;
			
			// aapt resource value: 0x7f050000
			public const int MainViewLayout = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int button0 = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int button1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button4 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int button5 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int button6 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int button7 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int button8 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int button9 = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int buttonA = 2131034138;
			
			// aapt resource value: 0x7f050029
			public const int buttonB = 2131034153;
			
			// aapt resource value: 0x7f05002c
			public const int buttonBSP = 2131034156;
			
			// aapt resource value: 0x7f050027
			public const int buttonC = 2131034151;
			
			// aapt resource value: 0x7f05001c
			public const int buttonD = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int buttonE = 2131034129;
			
			// aapt resource value: 0x7f05002f
			public const int buttonEnter = 2131034159;
			
			// aapt resource value: 0x7f05001d
			public const int buttonF = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int buttonG = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int buttonH = 2131034143;
			
			// aapt resource value: 0x7f050016
			public const int buttonI = 2131034134;
			
			// aapt resource value: 0x7f050020
			public const int buttonJ = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int buttonK = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int buttonL = 2131034146;
			
			// aapt resource value: 0x7f05002b
			public const int buttonM = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int buttonN = 2131034154;
			
			// aapt resource value: 0x7f050017
			public const int buttonO = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int buttonP = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int buttonQ = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int buttonR = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int buttonS = 2131034139;
			
			// aapt resource value: 0x7f05002e
			public const int buttonSpace = 2131034158;
			
			// aapt resource value: 0x7f050024
			public const int buttonSwitch = 2131034148;
			
			// aapt resource value: 0x7f050013
			public const int buttonT = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int buttonU = 2131034133;
			
			// aapt resource value: 0x7f050028
			public const int buttonV = 2131034152;
			
			// aapt resource value: 0x7f050010
			public const int buttonW = 2131034128;
			
			// aapt resource value: 0x7f050026
			public const int buttonX = 2131034150;
			
			// aapt resource value: 0x7f050014
			public const int buttonY = 2131034132;
			
			// aapt resource value: 0x7f050025
			public const int buttonZ = 2131034149;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
